name: Bun Test

on:
  workflow_dispatch:

jobs:
  print-hello-world:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"