name: Nuclei - Vulnerability Scan

on:
  workflow_dispatch:

jobs:
  amass-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4.0.0

      - name: Amass - Enumeration
        uses: hjvoid/amass-action@main
        with:
          domain: http:139.162.215.138/wp-admin/

      - name: Extract domains from Amass text file
        run: sh ./extract_domains.sh amass.txt

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: amass_domains.txt
          path: amass_domains.txt

  nuclei-scan:
    runs-on: ubuntu-latest
    needs: amass-scan
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: amass_domains.txt

      - name: Display structure of downloaded files
        run: 
          ls -R
          
      - name: Nuclei - Vulnerability Scan
        uses: projectdiscovery/nuclei-action@v1.0.7
        with:
          urls: amass_domains.txt
          flags: '- H "Cookie: wordpress_sec_90b1569174ff8a8001a104da46c9936e=hjvoid%7C1705165958%7CpZDDaSE3EB6yJ1ewPS9Bk6tfCWiVJAiMQ4DiWk3ZTYO%7Cc28acca3169425f5e1d58dfdacbd1134d8238df36a5e9d00adce2be7d8c60fb9; wordpress_test_cookie=WP%20Cookie%20check; wordpress_logged_in_90b1569174ff8a8001a104da46c9936e=hjvoid%7C1705165958%7CpZDDaSE3EB6yJ1ewPS9Bk6tfCWiVJAiMQ4DiWk3ZTYO%7Cc424ae0a0928fbdc3899a202f694eb00884d7696fab8f666959fe902694d7c81"'

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nuclei.log
          path: nuclei.log

      - name: GitHub Security Dashboard Alerts update
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: nuclei.sarif
