name: Nuclei - Vulnerability Scan

on:
  workflow_dispatch:

jobs:
  amass-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4.0.0

      - name: Amass - Enumeration
        uses: hjvoid/amass-action@main
        with:
          domain: owasp.org

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: amass.txt
          path: amass.txt

  nuclei-scan:
    runs-on: ubuntu-latest
    needs: amass-scan
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: amass.txt
      - name: Nuclei - Vulnerability Scan
        uses: projectdiscovery/nuclei-action@v1.0.7
        with:
          urls: amass.txt
      
      - name: Display structure of downloaded files
        run: 
          ls -R
      

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nuclei.log
          path: nuclei.log

      - name: GitHub Security Dashboard Alerts update
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: nuclei.sarif
