name: Nuclei - Vulnerability Scan

on:
  workflow_dispatch:

jobs:
  amass-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: uses: actions/setup-go@v5.0.0
      - run: |
        go env -w GO111MODULE=off      
        shell: bash

      - name: Amass - Enumeration
        uses: hjvoid/amass-action@main
        with:
          domain: http://178.79.135.71/
          brute: true
          ipv4: true
          alts: true

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: amass.txt
          path: amass.txt

  nuclei-scan:
    runs-on: ubuntu-latest
    needs: amass-scan
    steps:
      - uses: actions/checkout@v2

      - name: Nuclei - Vulnerability Scan
        uses: projectdiscovery/nuclei-action@v1.0.7
        with:
          urls: amass.txt

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nuclei.log
          path: nuclei.log

      - name: GitHub Security Dashboard Alerts update
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: nuclei.sarif